### ISSUE TITLE
Fix Geotiff extractor on SmartFarm Clowder

### ISSUE THREAD

**Issue by jonglee1** [geostreams/smartfarm#13]
Geotiff previewer extractor doesn't work on SmartFarm Clowder.

> Traceback (most recent call last):
  File "ncsa.geo.tiff.py", line 100, in process_message
    result = self.extractGeotiff(inputfile, fileid, filename, secret_key)
  File "ncsa.geo.tiff.py", line 220, in extractGeotiff
    success = gsclient.uploadGeotiff(geoserver_rest, self.gs_workspace, combined_name, uploadfile, filename, style, epsg, secret_key, self.proxy_on)
  File "/extractor/gsclient.py", line 121, in uploadGeotiff
    return self.geoserver_manipulation_proxy_off(geoserver_url, workspace, storename, filename, title, styleStr, projection)
  File "/extractor/gsclient.py", line 163, in geoserver_manipulation_proxy_off
    response_worksp = requests.get(self.restserver + 'workspaces/' + workspace, auth=(self.username, self.password))
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for "'https:/smartfarm.ncsa.illinois.edu/geoserver/rest/workspaces/601d8dcde4b0affc633642ac"

**Comment by jonglee1** [comment]
This error is caused by ".env" on the smartfarm vm contains bad URL of geoserver. 
The ".evn" has been fixed for shapefile extractor. However, the geotiff extractor needs to be restarted (rebuild) with new .env file. 

Fixed by restarting(rebuilding) the geotiff extractors by this command

> docker-compose up --detach --build ncsa_geotiff_preview
